# Generated by Django 4.0.4 on 2022-05-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_interesse_professor_projeto_tecnologia_tfc_cadeira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('proficiencia', models.CharField(max_length=50)),
                ('referencias', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='linguagens',
            field=models.ManyToManyField(to='portfolio.linguagem'),
        ),
    ]
