# Generated by Django 4.0.4 on 2022-05-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_linguagem_cadeira_linguagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='linguagens',
        ),
    ]
