# Generated by Django 4.0.4 on 2022-05-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_tecnologia_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='semestre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
