# Generated by Django 4.0.4 on 2022-06-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_cadeira_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfc',
            old_name='autor',
            new_name='autores',
        ),
        migrations.RenameField(
            model_name='tfc',
            old_name='sumario',
            new_name='imagem',
        ),
        migrations.AddField(
            model_name='tfc',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfc',
            name='orientadores',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfc',
            name='relatorio',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfc',
            name='resumo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfc',
            name='video',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
