# Generated by Django 4.0.4 on 2022-06-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_autor_tfc_autores_rename_sumario_tfc_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('imagem', models.CharField(max_length=500)),
            ],
        ),
    ]
